name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4961baaa5bb5b75b1f793323fd2136690941a49ee5be17602f55d21bdfe55cd5"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
