name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a54a165daa9caa98a5e7e3dfc8eb790688c9167ea54b093ece54dcd567b8cde7"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
