name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3a4f4fe14ea1c4f1f024d34707aa3d8a42878a172b9c8cccd0c4aac7d5ed7ef"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
