name = "othersmaybehere"
author = "<o>"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94b1e104e0ef3ab907ad5e7cf793ba93fdebd7cfdf8c9364e2f860b1f723dbe8"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
